# Generated by Django 4.1 on 2022-08-26 22:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_band_active_band_biography_band_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='description',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annonce',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='annonce',
            name='type',
            field=models.CharField(choices=[('Records', 'Disque'), ('Clothing', 'Vetements'), ('Posters', 'Affiche'), ('Miscelleanous', 'Divers')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annonce',
            name='year',
            field=models.IntegerField(default=2020, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2022)]),
            preserve_default=False,
        ),
    ]
