# Generated by Django 4.1 on 2022-08-27 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_annonce_description_annonce_sold_annonce_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='band',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.band'),
        ),
    ]
